### ISSUE TITLE
Question about plotting the distribution on dataset

### ISSUE THREAD

**Issue by wenmengliu** [mxbi/mlnd-capstone#1]
Hi Mikel,
Thanks for your sharing on your work. I have a question on plotting the distribution on train dataset. It takes me so long time to plt.hist(train_dataset). And I didn't make it. Are there any fast ways to make data visualization on the large dataset?

Thanks
Wenmeng

**Comment by mxbi** [comment]
@wenmengliu Sorry for the late response

Which column are you trying to plot? I just use

    plt.hist(df_train['trip_duration'], bins=50)

or something like that. If there is a lot of data, I will just plot the first N rows or use `df.sample()` to sample randomly. If you are trying to plot a non-floating point column then matplotlib may hang sometimes.
